# Generated by Django 4.1.6 on 2023-02-06 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cvv',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
