# Generated by Django 4.1.6 on 2023-02-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiry',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
